artifacts_root : artifacts

data_ingestion  : 
  SQLite_URL      : "https://github.com/Vampaxx/BIRD_benchmark_SQL/blob/main/artifacts/movies_4.sqlite"
  SQLite_dir      : artifacts/SQLite_database
  SQLite_file     : artifacts/SQLite_database/movies_4.sqlite
  data_URL        : "https://github.com/Vampaxx/BIRD_benchmark_SQL/blob/main/artifacts/train.json"
  data_dir        : artifacts/data
  data_file_path  : artifacts/data/train.json
  train_file_path : artifacts/data/train_data.json 
  test_file_path  : artifacts/data/test_data.json
  few_shots_path  : artifacts/data/few_shots.json

data_splitting:
  data_file_path  : artifacts/data/train.json
  train_file_path : artifacts/data/train_data.json 
  test_file_path  : artifacts/data/test_data.json
  few_shots_path  : artifacts/data/few_shots.json
